name: Docs Sync

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

       # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.0.2
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.0.2
        with:
         rdme: docs ./documentation/Authentication --key=rdme_xn8s9hccadc97d600faa34896ed8d52f7143fea4aead8795030765284fe0b91cc57219 --version=3.0

       # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.0.2
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.0.2
        with:
         rdme: docs ./documentation/Best-Practices --key=rdme_xn8s9hccadc97d600faa34896ed8d52f7143fea4aead8795030765284fe0b91cc57219 --version=3.0  

          # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.0.2
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.0.2
        with:
         rdme: docs ./documentation/Best-Practices --key=rdme_xn8s9hccadc97d600faa34896ed8d52f7143fea4aead8795030765284fe0b91cc57219 --version=3.0  
      
        # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.0.2
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.0.2
        with:
         rdme: docs ./documentation/Examples --key=rdme_xn8s9hccadc97d600faa34896ed8d52f7143fea4aead8795030765284fe0b91cc57219 --version=3.0  

          # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.0.2
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.0.2
        with:
         rdme: docs ./documentation/General --key=rdme_xn8s9hccadc97d600faa34896ed8d52f7143fea4aead8795030765284fe0b91cc57219 --version=3.0  

          # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.0.2
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.0.2
        with:
         rdme: docs ./documentation/Getting-Started --key=rdme_xn8s9hccadc97d600faa34896ed8d52f7143fea4aead8795030765284fe0b91cc57219 --version=3.0  

          # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.0.2
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.0.2
        with:
         rdme: docs ./documentation/Overview --key=rdme_xn8s9hccadc97d600faa34896ed8d52f7143fea4aead8795030765284fe0b91cc57219 --version=3.0 
         
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.0.2
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.0.2
        with:
         rdme: docs ./documentation/Quick-Start --key=rdme_xn8s9hccadc97d600faa34896ed8d52f7143fea4aead8795030765284fe0b91cc57219 --version=3.0   